---
- name: Build and Deploy Java Web Application with Maven to Tomcat
  hosts: webservers
  remote_user: devops
    # become: true  # Run tasks with sudo (if needed)

  tasks:
    - name: Build the Web Application with Maven
      ansible.builtin.command: /maven/apache-maven-3.9.6/bin/mvn clean package
      become: false
      args:
        chdir: ../src/main/java/com/mycompany/app/
      when: inventory_hostname == 'localhost'
   
    - name: Copy the Generated .war file to Tomcat Webapps Directory
      become: false
      copy:
        src: ../src/main/java/com/mycompany/app/target/my-app-1.0-SNAPSHOT.war
        dest: /u01/tomcat/webapps/


    - name: Restart Tomcat
      become_user: tomcat
      service:
        name: tomcat
        state: restarted

