---
- name: Build and Deploy Java Web Application with Maven to Tomcat
  hosts: webservers
  remote_user: devops
  become: true  # Run tasks with sudo (if needed)

  tasks:
    # - name: Build the Web Application with Maven
    #  command: mvn clean package
    #  args:
    #    chdir: /var/lib/jenkins/workspace
   
    - name: Change to the desired directory
      ansible.builtin.command: "cd ../; pwd"
      args:
        chdir: src/main/java/com/mycompany/app

    - name: Run your command (e.g., Maven)
      ansible.builtin.command: "mvn clean package"

    - name: Copy the Generated .war file to Tomcat Webapps Directory
      copy:
        src:  src/main/java/com/mycompany/app/target/my-app-1.0-SNAPSHOT.war
        dest: /u01/tomcat/webapps/

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted

