---
- name: Build and Deploy Java Web Application with Maven to Tomcat
  hosts: 
    - webservers
    - localhost
  remote_user: devops
  become: true  # Run tasks with sudo (if needed)

  tasks:
    - name: Build the Web Application with Maven
      ansible.builtin.command: mvn clean package
      become: false
      args:
        chdir: ./src/main/java/com/mycompany/app/
      when: inventory_hostname == 'localhost'
   
    - name: Copy the Generated .war file to Tomcat Webapps Directory
      copy:
        src: ./src/main/java/com/mycompany/app/target/my-app-1.0-SNAPSHOT.war
        dest: /u01/tomcat/webapps/
      when: inventory_hostname == 'webservers'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
      when: inventory_hostname == 'webservers'

