---
- name: Install Apache Tomcat10 using ansible
  hosts: webservers
  remote_user: devops
  become: true
  tasks:
 
    - name: Install OpenJDK
      package:
        name: java-11-openjdk
        state: present      
 
    - name: Create a Tomcat Directory
      file:
        path: /u01/tomcat
        owner: root
        group: root
        mode: 777
        recurse: yes
 
    - name: Download & Unarchive tomcat10 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz
        dest: /u01/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /u01/tomcat
        owner: root
        group: root
        mode: "u+rwx,g+rwx,o=rwx"
        recurse: yes
        state: directory
 
    - name: Copy Tomcat service from local to remote
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/
        mode: 777
 
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
